plone:
  image: eeacms/plone
  ports:
  - "8080:8080"
  links:
  - postgres
  environment:
  - BUILDOUT_EGGS=RelStorage psycopg2 david.stuff
  - BUILDOUT_REL_STORAGE=type postgresql \n host postgres \n dbname datafs \n user zope \n password zope
  - SOURCE_DAVID_STUFF=fs david.stuff
  volumes:
  - ./src:/opt/zope/src

postgres:
  image: eeacms/postgres
  environment:
  - POSTGRES_DBNAME=datafs
  - POSTGRES_DBUSER=zope
  - POSTGRES_DBPASS=zope
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=secret
